---

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'

- name: get rust installer
  get_url:
    url: "https://sh.rustup.rs"
    dest: /tmp/rustup.sh
    mode: 0775

- name: run rust installer
  command: "/tmp/rustup.sh -y"

- name: install dependencies
  command: "cargo install --force {{ item }}"
  loop:
    # - bat
    - bandwhich
    - exa
    - ripgrep

