---

- name: install plugins
  become: true
  become_user: "{{ user }}"
  shell: "omf install {{ item }}"   
  args:
    executable: fish
  with_items:
    - ansible
    - await
    - aws
    - bang-bang
    - battery
    - brew
    - docker-machine
    - extract
    - foreign-env
    - getopts
    - hash
    - license
    - node-binpath
    - nvm
    - osx
    - peco
    - python
    - rustup
    - rvm
    - tab
    - thefuck
    - vcs
    - vi-mode
    - virtualfish
    - weather
    - wttr
  ignore_errors: yes

- name: install python virtualfish library
  become: true
  pip:
      name: virtualfish
      state: present


- name: install debian-specific plugins
  become: true
  become_user: "{{ user }}"
  shell: "omf install {{ item }}"   
  args:
    executable: fish
  with_items:
    - apt
  when: ansible_os_family == 'Debian'
  ignore_errors: yes

- name: install macOS-specific plugins
  become: true
  become_user: "{{ user }}"
  shell: "omf install {{ item }}"   
  args:
    executable: fish
  with_items:
    - brew
    - cask
    - osx
  when: ansible_os_family == 'Darwin'
  ignore_errors: yes
