---

- name: download oh-my-fish
  become: true
  become_user: "{{ user }}"
  get_url:
    url: "https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"
    dest: "/tmp/fish-installer"

- name: remove existing oh-my-fish install
  become: true
  become_user: "{{ user }}"
  file:
    state: absent
    path: "/home/{{ user }}/.local/share/omf"

- name: install oh-my-fish
  become: true
  become_user: "{{ user }}"
  shell: "fish /tmp/fish-installer --noninteractive --path=/home/{{ user }}/.local/share/omf --config=/home/{{ user }}/.config/omf 2> /dev/null"
