---

- name: user | create user
  become: true
  user:
    name: "{{ user }}"
    append: yes
    createhome: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ user }}@{{ ansible_fqdn }}"
    state: present

- name: user | add groups
  become: true
  user:
    name: "{{ user }}"
    append: yes
    groups: "{{ extra_groups | join(',', ) }}"
  when: extra_groups is defined

- name: groups on macOS
  become: true
  user:
    name: "{{ user }}"
    append: yes
    groups: "staff,admin"
  when: ansible_os_family == 'Darwin'
