---

- name: shell | get shell absolute path
  shell: "which {{ user_shell }}"
  register: shell_path

- name: user | create user
  become: true
  user:
    name: "{{ user }}"
    append: yes
    createhome: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ user }}@{{ ansible_fqdn }}"
    shell: "{{ shell_path.stdout }}"
    state: present

- name: user | set shell
  become: true
  user:
    name: "{{ user }}"
    shell: "{{ shell_path.stdout }}"

- name: user | add groups
  become: true
  user:
    name: "{{ user }}"
    append: yes
    groups: "{{ extra_groups | join(',', ) }}"
  when: extra_groups is defined
