---

- name: common-server hosts | internal /etc/hosts
  become: yes
  lineinfile:
    backup: yes
    dest: /etc/hosts
    regexp: '.*{{ item.hostname }}$'
    line: "{{ item.address }} {{item.hostname}}"
    state: present
  when: (fellow_hosts is defined) and
        (item != inventory_hostname)
  with_items: fellow_hosts
  notify: common-server | restart networking

- name: common-server hosts | external /etc/hosts
  become: yes
  lineinfile:
    backup: yes
    dest: /etc/hosts
    regexp: '.*{{ item.hostname }}$'
    line: "{{ item.address }} {{item.hostname}}"
    state: present
  when: (external_hosts is defined) and
        (item != inventory_hostname)
  with_items: external_hosts
  notify: common-server | restart networking

- name: common-server hosts | /etc/hosts from inventory
  become: yes
  lineinfile:
    backup: yes
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  when: (hostvars[item].ansible_default_ipv4.address is defined) and
        (item != inventory_hostname)
  with_items: groups['all']
  notify: common-server | restart networking
