---

- name: clone dotfiles
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/feltnerm/dotfiles.git"
    version: "dotfiles2"
    dest: "{{ dotfiles_home }}"
    force: yes
    clone: yes
    update: yes
    recursive: yes

- name: install dotfiles
  become_user: "{{ user }}"
  shell: ./install chdir="{{ dotfiles_home }}"
  register: dotfiles_output

- name: dotbot output 
  debug:
    msg: "{{ item }}"
  with_items: "{{ dotfiles_output.stdout_lines }}"
