# Install some helpful system packages
---

- name: apt | update cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 43200

- name: apt | unnecessary system packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - chef
    - puppet

- name: apt | aptitude
  become: true
  apt:
    pkg: 'aptitude'
    state: present

- name: apt | upgrade
  become: true
  apt:
    upgrade: 'yes'

- name: apt | common system packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - ack
    - bash
    - build-essential
    - cmake
    - cowsay
    - curl
    - default-jre
    - docker
    - dstat
    - editorconfig
    - exiftool
    - ffmpeg
    - figlet
    - fish
    - flac
    - fortune
    - ghostscript
    - git
    # - git-lfs
    - htop
    - imagemagick
    - jq
    # - keybase
    - keychain
    - libz-dev
    - lnav
    - lsof
    - lynx
    - mc
    - mosh
    - mtr-tiny
    - nano
    - ncdu
    - peco
    - ranger
    - rsync
    - siege
    - scrypt
    - surfraw
    - shellcheck
    - software-properties-common
    - sysstat
    - tig
    - tmux
    - tree
    - unp
    - unzip
    - urlview
    - vim
    - wget
    - zip

- name: apt | check removed
  become: true
  shell: apt-get -y --dry-run autoremove | grep -q "0 to remove"
  args:
    warn: no
  register: check_autoremove
  ignore_errors: True
  changed_when: False

- name: apt | remove packages
  become: true
  command: apt-get -y autoremove
  when: "check_autoremove.rc != 0"

- name: apt | clean
  become: true
  command: apt-get clean
