# base/tasks/time.yml

# ntpq --peers  # http://time.to.pullthepl.ug/blog/2012/8/29/easy-ntp-stats-without-ntpstat/
---

- name: apt | openntp
  become: true
  apt:
    pkg: openntpd
    state: present

- name: service | openntpd enabled
  become: true
  service:
    name: openntpd
    enabled: yes

- name: service | openntpd started
  become: true
  service:
    name: openntpd
    state: started

- name: set locale
  become: true
  command: /usr/sbin/update-locale LANG={{ locale }}

- name: set /etc/localtime
  become: true
  file: src=/usr/share/zoneinfo/{{ time_zone }} dest=/etc/localtime state=link

- name: time | current timezone
  become: true
  shell: cat /etc/timezone
  register: current_zone

- name: time | configure timezone
  become: true
  copy:
    content: "{{ time_zone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: current_zone.stdout != time_zone
  register: configure_time_zone


