---

- name: install pypy repository
  become: true
  apt_repository:
    repo: ppa:pypy/ppa
    state: present

- name: install pypy
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - pypy
    - pypy-dev
    - python-cffi

- name: install python and python-dev
  become: true
  apt:
    name: "python{{ item[1] }}{{ item[0] }}"
    state: present
  with_nested:
    - [ '', '-dev']
    - [ '3', '' ]
