# @todo: why does this suck for python 3 on mac?
---

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'
