# @todo: why does this suck for python 3 on mac?
---

- name: get pip installer
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: /tmp/get-pip.py
    mode: 0755

- name: Download ez_setup.py
  get_url:
    url: "https://bootstrap.pypa.io/ez_setup.py"
    dest: /tmp/ez_setup.py
    mode: 0755

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'

- name: install easy_install from source
  shell: "{{ item[0] }}{{ item[1] }} /tmp/ez_setup.py"
  with_nested:
    - [ 'python' ]
    - [ '', '3' ]

- name: install pip from source
  shell: "{{ item[0] }}{{ item[1] }} /tmp/get-pip.py"
  with_nested:
    - [ 'python' ]
    - [ '' ]

- name: Install pip tools
  pip:
    name: "{{ item[1] }}"
    executable: "pip{{ item[0] }}"
    state: present
  with_nested:
    - [ '' ]
    - [ 'wheel', 'certifi', 'pyopenssl', 'pyasn1', 'ndg-httpsclient' ]

- name: install Python tools
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pbr
    - tox
    - virtualenv
    - virtualfish
    - virtualenvwrapper
    - wheel
