---

- name: create code directory
  become: true
  become_user: "{{ user }}"
  file:
      path: "{{ user_home }}/code"
      state: directory

- include: "python.yml"
- include: "node.yml"
- include: "rust.yml"
- include: "rvm.yml"
