---

- name: get nvm
  become: true
  become_user: "{{ user }}"
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh
    dest: /tmp/nvm-install
    mode: 0755

- name: get fish path
  become: true
  become_user: "{{ user }}"
  shell: which fish
  register: fish_path

- name: install nvm
  become: true
  become_user: "{{ user }}"
  shell: /tmp/nvm-install

- name: install node(s)
  become: true
  become_user: "{{ user }}"
  shell: "nvm install {{ item }}"
  args:
    executable: "{{ fish_path.stdout }}"
  with_items:
    - 4
    - 5
    - 6
    - 7
    - 8

- name: set current node version
  become: true
  become_user: "{{ user }}"
  shell: nvm use 8
  args:
    executable: "{{ fish_path.stdout }}"

- name: set system node version
  become: true
  become_user: "{{ user }}"
  shell: nvm alias default 8
  args:
    executable: "{{ fish_path.stdout }}"

- name: install global npm packages
  become: true
  become_user: "{{ user }}"
  shell: "npm install -g {{ item }}"
  args:
    executable: "{{ fish_path.stdout }}"
  with_items:
    - elm
    - elm-oracle
    - elm-test
    - emoj
    - eslint
    - eslint-config-standard
    - eslint-config-standard-react
    - eslint-plugin-promise
    - eslint-plugin-react
    - eslint-plugin-standard
    - eslint_d
    - git-recall
    - gmplayer
    - iectrl
    - ievims
    - loadtest
    - mapscii
    - nodemon
    - npm-check-updates
    - nyancat
    - prettier
    - prettier-standard
    - regexgen
    - serverless
    - standard
    - spoof
    - stylelint
    - textlint
    - textlint-rule-rousseau
    - textlint-rule-alex
    - textlint-rule-spellchecker
    - textlint-rule-write-good
    - travis-watch
    - wifi-password
    - write-good
    - yarn
