---

- name: get nvm
  become: true
  become_user: "{{ user }}"
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh
    dest: /tmp/nvm-install
    mode: 0755

- name: get shell path
  become: true
  become_user: "{{ user }}"
  shell: which zsh
  register: shell_path

- name: install nvm
  become: true
  become_user: "{{ user }}"
  shell: /tmp/nvm-install

- name: install node(s)
  become: true
  become_user: "{{ user }}"
  shell: "nvm install {{ item }}"
  args:
    executable: "{{ shell_path.stdout }}"
  with_items:
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

- name: set current node version
  become: true
  become_user: "{{ user }}"
  shell: nvm use 10
  args:
    executable: "{{ shell_path.stdout }}"

- name: set system node version
  become: true
  become_user: "{{ user }}"
  shell: nvm alias default 10
  args:
    executable: "{{ shell_path.stdout }}"

- name: install global npm packages
  become: true
  become_user: "{{ user }}"
  shell: "npm install -g {{ item }}"
  args:
    executable: "{{ shell_path.stdout }}"
  with_items:
    - elm
    - elm-oracle
    - elm-test
    - emoj
    - eslint
    - eslint_d
    - eslint-config-standard
    - eslint-config-standard-react
    - eslint-plugin-import
    - eslint-plugin-node
    - eslint-plugin-promise
    - eslint-plugin-react
    - eslint-plugin-standard
    - eslint_d
    - ghwd
    - git-recall
    - gmplayer
    - iectrl
    - ievms
    - jsctags
    - loadtest
    - mapscii
    - microtime
    - nettime
    - nodemon
    - npm-check-updates
    - npm-merge-driver
    - nyancat
    - prettier
    - prettier
    - prettier-eslint
    - prettier-standard
    - pretty-diff
    - readme
    - regexgen
    - serverless
    - standard
    - spoof
    - stylelint
    - svgo
    - terminal-image-cli
    - tern
    - tern-jsx
    - textlint
    - textlint-rule-rousseau
    - textlint-rule-alex
    - textlint-rule-spellchecker
    - textlint-rule-write-good
    - travis-watch
    - typescript
    - vtop
    - wifi-password
    - wopr
    - write-good
    - yarn
