---

- name: install Python tools
  pip:
    name: "{{ item[1] }}"
    executable: "pip{{ item[0] }}"
    state: latest
  with_nested:
    - [ '', '3' ]
    - [ 'autopep8', 'glances', 'http-prompt', 'neovim', 'pbr', 'pydf', 'pycodestyle', "python-language-server", 'tox', 'virtualenv', 'virtualfish', 'virtualenvwrapper', 'wheel', 'xkcdpass' ]
