---

- name: update and upgrade homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

# @todo: add Brewfile (optional?)
- name: tap
  homebrew_tap:
    state: present
    tap: "{{ item }}"
  with_items:
    - boz/repo
    - c-bata/kube-prompt
    # - homebrew/cask-cask
    - homebrew/cask-fonts
    - homebrew/cask-versions
    - homebrew/bundle
    - homebrew/services
    - moncho/dry
    - thoughtbot/formulae
    - universal-ctags/universal-ctags
    - wallix/awless
    - wagoodman/dive

# dependency
- name: install casks
  homebrew_cask:
    upgrade_all: yes
    name: xquartz
    state: present

- name: install apps
  homebrew:
    upgrade_all: yes
    name:
      - ack
      - archey
      - aspell
      - awscli
      - awless
      - bash
      - bat
      - bitwarden
      - boz/repo/kail
      - caddy
      - ccls
      - checkstyle
      - clojure-lsp
      - cmake
      - coreutils
      - cowsay
      - curl
      - diff-so-fancy
      - dive
      - dry
      - docker
      - editorconfig
      - exiftool
      - fd
      - ffmpeg
      - figlet
      - findbugs
      - findutils
      - fish
      - flac
      - fortune
      - fpp
      - ghostscript
      - git
      - git-lfs
      - gitsh
      - git-quick-stats
      - graphviz
      - hexyl
      - htop-osx
      - hub
      - imagemagick
      - ispell
      - jq
      - keychain
      - kubectl
      - kubectx
      - kubernetes-helm
      - kube-prompt
      - languagetool
      - llvm
      - lnav
      - lsof
      - lynx
      - mc
      - mosh
      - mtr
      - ncdu
      - noti
      - peco
      - pdfgrep
      - pidof
      - pmd
      - pt
      - ranger
      - ripgrep
      - rsync
      - siege
      - scrypt
      - shellcheck
      - selecta
      - speedtest-cli
      - stern
      - surfraw
      - tig
      - thefuck
      - tmux
      - toilet
      - trash
      - tree
      - unzip
      - urlview
      - vegeta
      - wget
      - wrk
      - wordnet
    state: present

- name: install HEAD packages
  homebrew:
    upgrade_all: yes
    name: 'universal-ctags'
    state: 'head'

- name: install completions
  homebrew:
    upgrade_all: yes
    name:
      - brew-cask-completion
      - launchctl-completion
      - open-completion
      - pip-completion
    state: present

- name: install casks
  homebrew_cask:
    state: present
    # @todo: re-add in ansible 2.2
    upgrade_all: yes
    install_options: "appdir=/Applications"
    name:
      - amethyst
      - caffeine
      - colloquy
      - cyberduck
      - docker-toolbox
      - electric-sheep
      - firefox
      - flux
      - google-chrome
      - karabiner
      # - keybase
      - lastfm
      - lastpass
      - macdown
      - sequel-pro
      - slack
      - spectacle
      - spotify-notifications
      - totalspaces
      - tunnelblick
      - vagrant
      - vim
      - virtualbox
      - virtualbox-extension-pack
      - visual-studio-code
      - vlc

- name: install quicklook plugins
  homebrew_cask:
    upgrade_all: yes
    name:
      - qlcolorcode
      - qlmarkdown
      - quicklook-json
      - quicklook-csv
      - qlstephen
    state: present

- name: install fonts
  homebrew_cask:
    upgrade_all: yes
    name:
      - font-anonymous-pro-for-powerline
      - font-consolas-for-powerline
      - font-dejavu-sans-mono-for-powerline
      - font-droid-sans-mono-for-powerline
      - font-fira-mono-for-powerline
      - font-inconsolata-dz-for-powerline
      - font-meslo-lg-for-powerline
      - font-sauce-code-powerline
      - font-source-code-pro
      - font-source-sans-pro
      - font-source-serif-pro
    state: present

# - name: install casks apps
#   homebrew:
#     name: "{{ item }}"
#     state: linked
#   with_items:
#     - docker


