---

# @todo: not sure how i feel about downloading this and
# running it as `sudo`
- name: download macOS defaults script
  become_user: "{{ user }}"
  get_url:
    url: https://raw.githubusercontent.com/mathiasbynens/dotfiles/master/.macos
    dest: /tmp/macos
    mode: 0755

- name: set macOS defaults
  become_user: "{{ user }}"
  shell: /tmp/macos

# any overrides for  the .macos script should go here so they're documented
- name: set macOS defaults user overrides
  become_user: "{{ user }}"
  osx_defaults:
    domain: "{{ item.domain }}" 
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value:  "{{ item.value }}"
  with_items: "{{ osx_default_overrides }}"

- name: set timezone
  become: true
  shell: systemsetup -settimezone "{{ mac_time_zone }}" > /dev/null

