---

- name: get rvm
  become: true
  become_user: "{{ user }}"
  get_url:
    url: https://get.rvm.io
    dest: /tmp/rvm
    chmod: 0775

- name: install rvm
  become: true
  become_user: "{{ user }}"
  shell: /tmp/rvm --ruby
