- name: set ~ on macos
  set_fact:
    user_home: "/Users/{{ user }}"
  when: ansible_os_family == 'Darwin'

- name: set ~ on *nix
  set_fact:
    user_home: "/home/{{ user }}"
  when: ansible_os_family != 'Darwin'

- name: debug user ~
  debug:
    var: user_home
