---

- name: install Vundle
  become_user: "{{ user }}"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ user_home }}/.vim/bundle/Vundle.vim"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install vundle plugins
  become_user: "{{ user }}"
  shell: "vim +PluginInstall +qall"
