---

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'

- name: install Vundle
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ user_home }}/.vim/bundle/Vundle.vim"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install vundle plugins
  become: yes
  become_user: "{{ user }}"
  shell: "vim +PluginInstall +qall"
