---

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'

# - name: install vim-plug
#   become: yes
#   become_user: "{{ user }}"
#   git:
#     repo: https://github.com/VundleVim/Vundle.vim.git
#     dest: "{{ user_home }}/.vim/bundle/Vundle.vim"
#     clone: yes
#     update: yes
#     recursive: yes
#     force: yes

- name: install vim-plug
  become: yes
  become_user: "{{ user }}"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ user_home }}/.vim/autoload/plug.vim"

- name: install vim plugins
  become: yes
  become_user: "{{ user }}"
  shell: "vim +PlugInstall! +qall"
