---

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'

- name: ensure vim autoload directory exists
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ user_home }}/.vim/autoload/"
    state: directory
    mode: 0755

- name: install vim-plug
  become: yes
  become_user: "{{ user }}"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ user_home }}/.vim/autoload/plug.vim"

- name: update vim plugins
  become: yes
  become_user: "{{ user }}"
  shell: "vim +PlugUpgrade! +qall"

- name: install vim plugins
  become: yes
  become_user: "{{ user }}"
  shell: "vim +PlugInstall! +qall"

- name: update vim plugins
  become: yes
  become_user: "{{ user }}"
  shell: "vim +PlugUpdate! +qall"
