# playbok/desktop.yml
# Setup a base desktop environment on a local system

- include: bootstrap.yaml
- include: dev-env.yml

- hosts: all
  roles:
     - role: common
     - role: games
  vars:
    - locale: 'en_US.UTF-8'
    - time_zone: 'US/Central'
    - mac_time_zone: 'America/Chicago'

