# playbook/update.yml
# Just update all the software
---

- hosts: all
  roles:
   - role: common
   - role: debian
     when: ansible_os_family == 'Debian'
   - role: arch
     when: ansible_os_family == 'Archlinux'
   - role: macos
     when: ansible_os_family == 'Darwin'
   - role: shell
   - role: dotfiles
   - role: fish
   - role: dropbox
   - role: go
   - role: java
   - role: node
   - role: python
   - role: ruby
   - role: rust
   - role: vim
   - role: neovim
   - role: dev-env
   - role: games
