---

- hosts: whatbox
  tasks:
    - name: backup symlinks
      shell: "tar -czf /home/plugitin/backup/finished-$(date -u '+%Y-%m-%d_%HZ').tar.gz /home/plugitin/finished "

- hosts: nalanda vars_prompt:
    - name: "gmupload"
      prompt: "Would you like to upload to Google Music after sync and tag? (yes/no)"
      default: "yes"
    - name: "cleanup_nalanda"
      prompt: "Would you like to cleanup nalanda after sync? (yes/no)"
      default: "no"
    - name: "backup_nalanda"
      prompt: "Would you like to run backups after sync? (yes/no)"
      default: "no"

  tasks:
    - name: rsync from whatbox
      command: "rsync --update --stats --human-readable --recursive --times \
                --owner --group --perms --cvs-exclude --devices --specials \
                --copy-links --copy-dirlinks \
                plugitin@ulysses.whatbox.ca:/home/plugitin/finished/ {{ stash }}/uploads/whatbox"
      register: rsync_result

    - name: result of rsyncing files from whatbox
      debug: var=rsync_result.stdout_lines

    - name: copy media
      command: mv "{{ stash }}/uploads/whatbox/{{ item }}/* {{ stash }}/library/{{ item }}"
      with_items:
        - "books"
        - "games"
        - "movies"
        - "other"
        - "pictures"
        - "tv"
        - "warez"

    - name: update tags with beets
      chdir: '{{ stash }}/uploads/whatbox/music'
      command: 'beet import --quiet --log={{ stash }}/_meta/logs/beet-import.log --nocopy .'

    - name: upload to google music
      command: 'gmupload --log {{ stash }}/uploads/whatbox/music'
      when: gmupload == "yes"

    - name: move into beets library
      chdir: '{{ stash }}/uploads/whatbox/music'
      command: 'beet import --quiet --log={{ stash }}/_meta/beet-import.log --noautotag .'

    - name: remove files that have changed from uploads
      when: cleanup_nalanda == "yes"
      shell: 'rm -rf /stash/library/uploads/whatbox/*'
      when: cleanup_nalanda == "yes"

    - name: run backups
      command: './stash/_scripts/backup.sh'
      when: backup_nalanda == "yes"

- hosts: whatbox
  vars_prompt:
    - name: "cleanup_whatbox"
      prompt: "Would you like to cleanup whatbox after sync? (yes/no)"
      default: "no"
  tasks:
    - name: cleanup whatbox
      shell: 'rm -rf ~/finished/*'
      when: cleanup_whatbox == "yes"
