---

- include: 'arch.yml'
  when: ansible_os_family == 'Archlinux'
- include: 'debian.yml'
  when: ansible_os_family == 'Debian'
- include: 'macos.yml'
  when: ansible_os_family == 'Darwin'


# ln -s ~/.vim ~/.config/nvim
- name: link vim folder
  file:
      state: link
      src: "{{ user_home }}/.vim"
      dest: "{{ user_home }}/.config/nvim"

# ln -s ~/.vimrc ~/.config/nvim/init.vim
- name: link vimrc
  file:
      state: link
      src: "{{ user_home }}/.vimrc"
      dest: "{{ user_home }}/.config/nvim/init.vim"

- name: neovim python support
  pip:
    name: "neovim"
    state: latest
